### ISSUE TITLE
Format the output of the code

### ISSUE THREAD

**Issue by HalfToothed** [HalfToothed/online-code-compiler#2]
Format the output of the code in output box, for better user understanding

**Comment by mdrehan369** [comment]
Assign this issue to me under hactoberfest 2024

**Comment by mdrehan369** [comment]
Can u explain me what kind of output format you need

**Comment by HalfToothed** [comment]
@mdrehan369  right now its very raw, we can add some syntax highlighting when output is error message with code

**Comment by mdrehan369** [comment]
Okay i got it!
