### ISSUE TITLE
[BUG]: when running code there is no response

### ISSUE THREAD

**Issue by relaxgameing** [HalfToothed/online-code-compiler#3]
here is the screenshot:
<img width="1512" alt="Screenshot 2024-10-26 at 6 58 36 PM" src="https://github.com/user-attachments/assets/f6ec7952-b178-4bf8-8ee4-31208e2545a6">

I would be happy to work on this issue

**Comment by HalfToothed** [comment]
because I have exceeded the DAILY quota for Submissions on my current plan.
@relaxgameing can you work on 
showing a modal popup with the error message when the API request fails, providing users with a clear, dismissible notification

**Comment by relaxgameing** [comment]
> because I have exceeded the DAILY quota for Submissions on my current plan.
> @relaxgameing can you work on 
> showing a modal popup with the error message when the API request fails, providing users with a clear, dismissible notification

Oh ok then you can assign me I will add a notification prompt that would show user the appropriate message

**Comment by HalfToothed** [comment]
@relaxgameing  i have assigned the issue to you 

for now just show a simple notification prompt when api fails
